
name: 'jaffle_shop_raw'
version: '0.1'
profile: 'jaffle_shop_sf'
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

seeds:
  jaffle_shop_raw:
    enabled: true
    database: RAW_JAFFLE
    schema: SEED